name: clima
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  geolocator: ^5.1.5
  http: ^0.12.0+3
  flutter_spinkit: "^4.1.1"
  flare_flutter: ^1.8.3
  flutter_icons: ^1.0.0+1
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/
  - assets/

  fonts:
  - family: Spartan MB
    fonts:
    - asset: fonts/SpartanMB-Black.otf
      weight: 900
  - family: DS DIGI
    fonts:
    - asset: fonts/DS-DIGI.TTF
      weight: 900